title: FerrumFIX
description: A free and open-source FIX implementation in Rust
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

github:
  is_project_page: true
  repository_url: https://github.com/ferrumfix/ferrumfix
  zip_url: http://example.com/download.zip
  another_url: another value

